# Usar a imagem do Node.js LTS Alpine como base para a construção
FROM node:lts-alpine AS build

# Criar diretório do aplicativo
WORKDIR /app

# Copiar os arquivos de manifesto de dependência do aplicativo para a imagem do contêiner
COPY package.json package-lock.json ./

# Instalar as dependências do aplicativo usando o comando `npm ci` em vez de `npm install`
RUN npm ci 

# Copiar o código-fonte do aplicativo para o contêiner
COPY --chown=node:node . .

# Construir o aplicativo
RUN npm run build

# Limpar o cache do npm
RUN npm cache clean --force

# Etapa final do build
FROM node:lts-alpine AS production
 
# Copiar o código empacotado da fase de construção para a imagem de produção
COPY --from=build /app/node_modules ./node_modules

# Expor a porta que o aplicativo vai usar
EXPOSE 5001

# Iniciar o servidor usando a versão de produção do aplicativo
CMD [ "node", "/index.js" ]
