on: push

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout Github Action' 
      uses: actions/checkout@master

    - name: 
      uses: actions/setup-node@v1
      with:
        node-version: '18.x'
    - name: 'npm install'
      run: |
        npm install

    - name: Deploy Azure App Service
      uses: azure/webapps-deploy@v2
      with:
        app-name: BackEndModernChef
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: .